const titulos = [
    'La busqueda del tesoro',
    '¿Acaso no puedo hacer?',
    '¡Oh cuan dulce es fiar en Cristo!',
    'Una enfermedad sin dolor',
    'El valor de la responsabilidad',
    'Los verdaderos hermanos de jesús',
    'La bendición de la mayordomia',
    'El naufrágo del Santa Maria de luján',
    '¿No es mi palabra como fuego?',
    'Roca de la eternidad',
    'Los zapatos de Zadan',
    'Una amistad a prueba de uniformes',
    'Un encuentro con los cansados',
    'El templo: ¿Manantial de vida o instrumento del enemigo)?',
    'Las capas de la cebolla',
    '¿No son falsas sus viciones?',
    'De su trono, mi Jesús',
    'El discurso de Abbe Pierre',
    'Las millas extras',
    'Un encuentro en la tormenta',
    'La maravilla más grande del Machu Picchu',
    'Las piezas del rompecabezas',
    '¿Quiero yo la muerte del impío?',
    'Día a día',
    'La ceguera de Giezi',
    'La resiliencia de Elie Wiesel',
    'Un encuentro con el fiordo',
    'Una cura natural',
    'El orden de las letras',
    '¿Piensan ustedes que yo no estoy actuando bien?',
    'Señor Jesús, el día ya se fue',
]

export { titulos }
