const titulos = [
    'El Dios que provee',
    'Será provisto',
    'La pregunta universal',
    'El cordero es la mayor provisión',
    'En la mesa del rey',
    'Mil formas de proveer',
    'Ningún bien nos faltará',
    'Provisión para el pobre',
    'El Dios que abre la mano',
    'Bendición en la casa de Dios',
    'Bendiciones sin limite',
    'La mano abierta de Dios',
    'Sabiduría para los rectos',
    '¿Cuál casa prefieres?',
    'Dios es nuestro refugio',
    'El juramento sigue pendiente',
    'Hasta que sobreabunde',
    'Fe a prueba de todo',
    'Respuesta anticipada',
    'Descanso para el alma',
    'Con las manos vacias',
    'Todo a tu disposición',
    'Vestidos de Cristo',
    'El que da recibe',
    'Un cheque para ti',
    'Negando la fe',
    'El postre está al final',
    'El remedio para la avaricia',
    'No hay lugar para la duda',
    'Cielo nuevo y tierra nueva',
    'Cosas que ojo no vio ni oido oyó',
]

export { titulos }
